import UserService from "./user/index";
import FormService from "./form/index";
import FormFieldService from "./form-field/index";
import FormSubmissionService from "./form-submission/index";
import EmailService from "./email/index";
import QuizService from "./quiz/index";
import QuizQuestionService from "./quiz-question/index";
import QuizAttemptService from "./quiz-attempt/index";
import QuizAnalyticsService from "./quiz-analytics/index";
import QuestionBankService from "./question-bank/index";

export const userService = new UserService();
export const formService = new FormService();
export const formFieldService = new FormFieldService();
export const formSubmissionService = new FormSubmissionService();
export const emailService = new EmailService();
export const quizService = new QuizService();
export const quizQuestionService = new QuizQuestionService();
export const quizAttemptService = new QuizAttemptService();
export const quizAnalyticsService = new QuizAnalyticsService();
export const questionBankService = new QuestionBankService();
